// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MultiplysvcClient is the client API for Multiplysvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MultiplysvcClient interface {
	Multiply(ctx context.Context, in *MultiplyRequest, opts ...grpc.CallOption) (*MultiplyReply, error)
}

type multiplysvcClient struct {
	cc grpc.ClientConnInterface
}

func NewMultiplysvcClient(cc grpc.ClientConnInterface) MultiplysvcClient {
	return &multiplysvcClient{cc}
}

func (c *multiplysvcClient) Multiply(ctx context.Context, in *MultiplyRequest, opts ...grpc.CallOption) (*MultiplyReply, error) {
	out := new(MultiplyReply)
	err := c.cc.Invoke(ctx, "/api.Multiplysvc/Multiply", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MultiplysvcServer is the server API for Multiplysvc service.
// All implementations must embed UnimplementedMultiplysvcServer
// for forward compatibility
type MultiplysvcServer interface {
	Multiply(context.Context, *MultiplyRequest) (*MultiplyReply, error)
	mustEmbedUnimplementedMultiplysvcServer()
}

// UnimplementedMultiplysvcServer must be embedded to have forward compatible implementations.
type UnimplementedMultiplysvcServer struct {
}

func (UnimplementedMultiplysvcServer) Multiply(context.Context, *MultiplyRequest) (*MultiplyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Multiply not implemented")
}
func (UnimplementedMultiplysvcServer) mustEmbedUnimplementedMultiplysvcServer() {}

// UnsafeMultiplysvcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MultiplysvcServer will
// result in compilation errors.
type UnsafeMultiplysvcServer interface {
	mustEmbedUnimplementedMultiplysvcServer()
}

func RegisterMultiplysvcServer(s grpc.ServiceRegistrar, srv MultiplysvcServer) {
	s.RegisterService(&Multiplysvc_ServiceDesc, srv)
}

func _Multiplysvc_Multiply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MultiplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultiplysvcServer).Multiply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Multiplysvc/Multiply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultiplysvcServer).Multiply(ctx, req.(*MultiplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Multiplysvc_ServiceDesc is the grpc.ServiceDesc for Multiplysvc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Multiplysvc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.Multiplysvc",
	HandlerType: (*MultiplysvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Multiply",
			Handler:    _Multiplysvc_Multiply_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/multiplysvc.proto",
}
